spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
           #- Path=/salchichon/**
            - Header=servicio, organzacion
          #filters:
          #  - RewritePath=/salchichon/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            #- Path=/license/**
            - Header=servicio, licensia
          #filters:
          #  - RewritePath=/license/(?<path>.*), /$\{path}



management:
  endpoints:
    web:
      exposure:
        include: "*"